New Capability of GPM GMI Radiance Data Assimilation
wrf-model/WRF pull request #1585
Opened 2021-11-19 03:15 UTC by xdmjolly

KEYWORDS: GPM-GMI, Radiance
SOURCE: Dongmei Xu (NUIST/NCAR)
DESCRIPTION OF CHANGES:
Add new capability to assimilate GPM-GMI Level-1 data in HDF5 format, which can be downloaded from https://gpm.nasa.gov/data/
LIST OF MODIFIED FILES:
	Modified:   Registry/registry.var
	Modified:   var/build/depend.txt
	Modified:   var/da/da_radiance/da_allocate_rad_iv.inc
	Modified:   var/da/da_radiance/da_deallocate_radiance.inc
	Modified:   var/da/da_radiance/da_initialize_rad_iv.inc
	Modified:   var/da/da_radiance/da_qc_rad.inc
	modified:   var/da/da_radiance/da_radiance.f90
	Modified:   var/da/da_radiance/da_radiance1.f90
	Modified:   var/da/da_radiance/da_radiance_init.inc
	Modified:   var/da/da_radiance/da_setup_radiance_structures.inc
	Modified:   var/da/da_radiance/module_radiance.f90
	Modified:   var/da/da_setup_structures/da_setup_obs_structures.inc
	Modified:   var/da/da_setup_structures/da_setup_structures.f90
	Modified:   var/run/VARBC.in
	Added: var/da/da_radiance/da_qc_gmi.inc
	Added: var/da/da_radiance/da_read_obs_hdf5gmi.inc
	Added: var/run/radiance_info/gpm-1-gmi.info
TESTS CONDUCTED: WRFDA regression tests ran successfully with gnu/ifort+mpt on Cheyenne.
RELEASE NOTE: A new capability to assimilate GPM-GMI radiance data
Shen, et al.，2021: Assimilation of GPM Microwave Imager Radiance data with the WRF Hybrid 3DEnVar System for the Prediction of Typhoon Chan-hom (2015), Atmospheric Research. 251, 105422.

2021-11-19 05:57 UTC, Plantain commented
This looks really good. Can you write a section for the user guide on it's usage? It looks like the GMI1B and GMI1A are required? I don't understand how the right scan times / regions are selected.

2021-11-23 03:48 UTC, liujake requested changes

2021-11-23 03:48 UTC, liujake commented on var/da/da_radiance/da_read_obs_hdf5gmi.inc
> +   !------------------------------------------------------------------------------
this line is too long, please change it to two lines.

2021-11-23 04:39 UTC, liujake approved these changes

2021-11-23 04:40 UTC, merged