make configure script more portable
wrf-model/WRF pull request #1871
Opened 2023-05-23 04:31 UTC by weiwangncar

TYPE: bug fix

KEYWORDS: configure script, use '=' vs '=='

SOURCE: Chris Bridgham

DESCRIPTION OF CHANGES:
Problem:
The newly added test in v4.5 in configure script could fail due to less portable use '==' as in 
```
if [ $rpc_type == "rpc" ]; then
```

Solution:
Change the above to
```
if [ $rpc_type = "rpc" ]; then
```

ISSUE: For use when this PR closes an issue.
Fixes #1869

LIST OF MODIFIED FILES: 
M     configure

TESTS CONDUCTED: 
1. Yes.
2. Are the Jenkins tests all passing?

RELEASE NOTE:

2023-05-23 21:31 UTC, islas submitted a review, later dismissed

2023-05-23 21:35 UTC, weiwangncar commented
@islas Thanks for approving this PR and welcome to the Github team!

2023-05-24 13:33 UTC, douglowe commented
There are more instances of this syntax causing problems noted in [https://github.com/wrf-model/WRF/issues/1817](https://github.com/wrf-model/WRF/issues/1817). Could these be addressed in this PR too?

2023-05-24 16:52 UTC, weiwangncar commented
> There are more instances of this syntax causing problems noted in #1817. Could these be addressed in this PR too?

@douglowe Are you referring to these lines:

      CURL="`$nx_config | awk '{for(i=1;i<=NF;i++){if($i == "-lcurl") {print $i} } }'`"
      GPFS="`$nx_config | awk '{for(i=1;i<=NF;i++){if($i == "-lgpfs") {print $i} } }'`"

2023-06-19 03:52 UTC, HathewayWill commented
@weiwangncar @douglowe 

I think also line 1046 of the configure file
`  if [ $rpc_type == "rpc" ]; then`

2023-06-28 21:33 UTC, weiwangncar commented
The regression test results:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           57
    Number of Simulations  : 158           150        0
    Number of Comparisons  : 95           86        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

2023-06-28 22:23 UTC, mgduda requested changes

2023-06-28 22:23 UTC, mgduda commented on configure
> +      GPFS="`$nx_config | awk '{for(i=1;i<=NF;i++){if($i = "-lgpfs") {print $i} } }'`"
I may be mistaken, but the if-test here is for `awk` and not `sh`, so I don't think these should be modified.

2023-06-28 22:23 UTC, mgduda commented on configure
> +        GPFS="`$nx_config | awk '{for(i=1;i<=NF;i++){if($i = "-lgpfs") {print $i} } }'`"
As above, the modified code here is an `awk` script and not shell, so we may want to consider reverting these changes.

2023-06-28 22:34 UTC, mgduda commented
> There are more instances of this syntax causing problems noted in #1817. Could these be addressed in this PR too?

Were these addressed already by PR #1735? From what I can tell (and I may be mistaken), the only remaining occurrence was at line 1046, which af8c2af8 corrects.

2023-06-28 22:36 UTC, mgduda commented
@weiwangncar I think if you were to reset the HEAD of your branch to af8c2af8, that would be sufficient.

2023-06-28 22:48 UTC, weiwangncar commented
> @weiwangncar I think if you were to reset the HEAD of your branch to [af8c2af](https://github.com/wrf-model/WRF/commit/af8c2af83e8157628d94fd25e40975320fc08d08), that would be sufficient.

@mgduda Should I do that in my local sandbox and push the change to the folk?

2023-06-28 22:53 UTC, mgduda commented
> > @weiwangncar I think if you were to reset the HEAD of your branch to [af8c2af](https://github.com/wrf-model/WRF/commit/af8c2af83e8157628d94fd25e40975320fc08d08), that would be sufficient.
> 
> @mgduda Should I do that in my local sandbox and push the change to the folk?

Correct. With the `fix-config` branch checked out in your clone, you can run:
```
git reset af8c2af
```
followed by a force-push to your remote repository.

2023-06-28 23:31 UTC, mgduda approved these changes
This looks good to me. I tried running the configure script with the `dash` shell. Although probably not all paths through the `configure` script were exercised, no errors turned up.

2023-06-28 23:36 UTC, weiwangncar commented
@islas Need to have your approval again...

2023-06-29 00:01 UTC, islas approved these changes

2023-06-29 00:04 UTC, merged