Improved ignores
wrf-model/WRF pull request #1978
Opened 2024-01-06 00:08 UTC by islas

TYPE: enhancement

KEYWORDS: ignores

SOURCE: internal

DESCRIPTION OF CHANGES:
Problem:
Many files are generated in the repo's directories and should be ignored to avoid accidental addition to commits.

Solution:
Ignore known file patterns

LIST OF MODIFIED FILES: 
M       .gitignore

TESTS CONDUCTED: 
No impact

RELEASE NOTE: 
Improved set of ignores

2024-01-06 01:50 UTC, weiwangncar commented
The regression test results:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           57
    Number of Simulations  : 158           150        0
    Number of Comparisons  : 95           86        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

2024-01-06 02:26 UTC, mgduda requested changes

2024-01-06 02:26 UTC, mgduda commented on .gitignore
> +rsl.error.*
The only change I'd suggest is to add an end-of-line character after the last line.

2024-01-08 22:40 UTC, mgduda approved these changes
Looks solid to me.

2024-01-09 01:40 UTC, weiwangncar approved these changes

2024-01-09 20:35 UTC, merged