Replace nonstandard isnan() call with value input checks instead
wrf-model/WRF pull request #2061
Opened 2024-06-07 19:15 UTC by islas

TYPE: bug fix

KEYWORDS: compilation, nonstandard

SOURCE: internal

DESCRIPTION OF CHANGES:
Problem:
PR #1944 introduced a nonstandard function call `isnan()` which breaks compilation for compilers which don't support this extension. 

Solution:
A potential alternative is to use the `ieee_is_nan()` call from `ieee_arithmetic`. As there is conditional compilation of this module which requires Fortran 2003 standard, an easier alternative is just to check the input values before calling `acos()`

2024-06-07 21:01 UTC, weiwangncar commented
The regression test results:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           57
    Number of Simulations  : 158           150        0
    Number of Comparisons  : 95           86        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

2024-08-07 03:45 UTC, weiwangncar submitted a review, later dismissed

2024-09-12 19:47 UTC, mgduda requested changes
As a final comment, I wonder whether the original code is correct? Would setting `angle = pi` be better when `tmp1 / tmp2` is less than `-1`?

2024-09-12 19:47 UTC, mgduda commented on phys/module_wind_mav.F
> +      endif
To match the style of the rest of the code, I'd suggest `end if` here.

2024-09-12 19:47 UTC, mgduda commented on phys/module_wind_mav.F
> +        angle = 0
If we're assigning to a `real`, I think it would be preferable to uses `0.` rather than `0`.

2024-09-12 19:47 UTC, mgduda commented on phys/module_wind_mav.F
> +      if ( tmp1 < -1 .or. tmp1 > 1 ) then
I think it would be preferable to use `-1._8` and `1._8`, since `tmp1` is a `real (kind = 8)` variable.

2024-09-12 23:43 UTC, islas commented
> As a final comment, I wonder whether the original code is correct? Would setting `angle = pi` be better when `tmp1 / tmp2` is less than `-1`?

I'm unsure. That does make sense, but  I was hesitant to modify the logic in a way that deviates from the original. Since the final result is a `logical`, there are probably more implications [than I understand] based on what a close-to or actual out of bounds evaluation should be.

2024-09-13 00:05 UTC, mgduda commented
Agreed that we shouldn't try to "correct" the computation, as we may be missing some important details.

As a final comment, I'd suggest trying to match the whitespace convention used in the rest of the `find_turb`: four spaces of indentation, and no space between the parentheses in conditional statements.

2024-09-13 00:30 UTC, islas commented
> trying to match the whitespace convention used in the rest of the `find_turb`: four spaces of indentation, and no space between the parentheses in conditional statements.

Fixed, though I do wish we had a format checker, as a significant portion of the file's code (and the original logic that this PR replaces) don't follow this.

2024-09-13 00:40 UTC, mgduda approved these changes

2024-09-13 04:02 UTC, weiwangncar approved these changes

2024-09-13 19:34 UTC, merged