Restructure alloc space calls into simpler smaller files
wrf-model/WRF pull request #2068
Opened 2024-06-14 22:31 UTC by islas

TYPE: enhancement

KEYWORDS: intel, compilation, llvm, memory

SOURCE: internal

DESCRIPTION OF CHANGES:
Problem:
The Intel oneAPI compilers (and others like nvhpc) struggle with some of the larger (15k+ lines of code) files within WRF. This causes intense memory usage that is not often available to the average user not in a resource-rich environment. This often limits compilation to single threaded if even possible or to a dedicated environment with enough memory if available. If neither of those is available to a user, they will be unable to use these configurations entirely.

Solution:
This PR focuses on the `module_alloc_space*` sections of code to reduce their individual file size to manageable levels. They are instead broken out into many smaller files as external subroutines, not requiring a wrapper module to house the subroutine call. The files are now fully generated source code from the registry, with the calls to the subroutines also being generated as well. This also makes it relatively easy to change the number of files generated from a source code perspective. Build rules would need to be modified accordingly as seen in these changes.

TESTS CONDUCTED: 
Attached to this PR are plots of the respective effects of theses changes. Changes were tested with intel and gcc compilers, but only intel memory usage is shown as it exacerbates the memory usage issue.

2024-06-14 22:35 UTC, islas commented
Highlighted is the region during compilation which memory usage spikes that this PR addresses (`module_alloc_space*`) before these changes take place :
![pre_alloc](https://github.com/wrf-model/WRF/assets/128631809/97820afb-0757-44b8-9bdf-1424a58c47c4)

This usage is then dropped when using this PR's edits :
![post_alloc_split](https://github.com/wrf-model/WRF/assets/128631809/7daab455-5273-4096-8d75-d521c53daf36)

Zooming in we can now see that allocs_ comprise a number of smaller compilation units :
![post_alloc_split_zoom](https://github.com/wrf-model/WRF/assets/128631809/1b112d8e-e49a-47e5-b415-6ab2a0fd1c36)

2024-08-07 08:15 UTC, weiwangncar commented
@islas This PR has not passed Jenkins tests at this time. The failed test is with the DA compilation.

2024-08-07 09:55 UTC, weiwangncar commented
I tested code before and after this PR, and model produces identical results in my test. Also with 4 processors, the compile time is about 12 minutes!

2024-08-08 10:40 UTC, weiwangncar commented
The regression test results:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           57
    Number of Simulations  : 158           150        0
    Number of Comparisons  : 95           86        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

2024-08-08 10:41 UTC, weiwangncar approved these changes

2024-09-19 22:09 UTC, mgduda requested changes
Just a few minor suggestions. Those aside, this looks good to me.

2024-09-19 22:30 UTC, islas commented on var/build/makefile
> -
Ah, must have deleted an extra line when getting rid of the .F90 rule I added then removed.

2024-09-24 19:52 UTC, mgduda approved these changes

2024-09-26 22:07 UTC, weiwangncar approved these changes

2024-09-26 22:20 UTC, merged