CMake PnetCDF Find Package
wrf-model/WRF pull request #2145
Opened 2024-12-18 23:53 UTC by islas

TYPE: enhancement

KEYWORDS: cmake, pnetcdf

SOURCE: internal

DESCRIPTION OF CHANGES:
Problem:
The CMake build does not support PnetCDF detection and thus the `external/io_pnetcdf/` code cannot be built.

Solution:
Write a FindPnetCDF.cmake package that provides the appropriate imported target to link against and does precursory library matching if there is a dependency on netCDF C. Update the cmake code in `external/io_pnetcdf/` to build, with minor adjustments that make the CMake and Make builds compatible.

The package uses the same rules of the netCDF packages, utilizing `pnetcdf-config` in the `PATH` as the source of information, or otherwise found via standard `find_package()` mechanics, e.g. `PnetCDF_ROOT`.

TESTS CONDUCTED: 
1. Tested CMake and Make builds with PnetCDF in environment on local machine and Derecho.

RELEASE NOTE: CMake PnetCDF Find Package

2025-11-14 18:53 UTC, amstokely approved these changes

2025-12-12 20:05 UTC, dudhia approved these changes, later dismissed

2025-12-16 19:16 UTC, islas commented
When you can, @mgduda could you review this PR for secondary approval?

2026-02-11 22:24 UTC, mgduda requested changes

2026-02-11 22:24 UTC, mgduda commented on external/io_pnetcdf/ext_pnc_put_dom_ti.code
> +  include "pnetcdf.inc"
Here and elsewhere, it might be nice to use single quotes for consistency with other Fortran `include` statements.

2026-02-12 20:01 UTC, mgduda requested changes

2026-02-12 20:01 UTC, mgduda commented on external/io_pnetcdf/field_routines.F90
> +#  include 'pnetcdf.inc'
Here and in several other places, it looks like these lines are still pre-processor directives.

2026-02-12 22:44 UTC, islas commented on external/io_pnetcdf/field_routines.F90
> +#  include 'pnetcdf.inc'
Not all need to be changed away from preprocessor directives. `wrf_io.F90` and the `*.code` files needed to since they are `cpp` preprocessed and then `m4` preprocessed and that syntax didn't quite fit with the compilation method of either make or cmake while keeping the C-style preprocessor directives.

That said, I may need to revert all or part of 26bf71a as single quotes are not allowed in the C include directive. Or everything just changed to Fortran include directives regardless. This however starts to get into modifying code _"somewhat"_ unrelated to the changes presented in this PR.

2026-02-12 23:08 UTC, mgduda commented
My apologies -- I think I was confused as to what was going on after the second commit. I originally meant to suggest switching to single quotes only for the preprocessing directives that had been changed to Fortran `include` statements.

2026-02-18 22:41 UTC, islas commented
@mgduda I believe this should be ready to review again

2026-02-18 23:40 UTC, mgduda approved these changes

2026-02-19 05:49 UTC, weiwangncar approved these changes

2026-02-19 19:13 UTC, merged